### ISSUE TITLE
Why is the reward of leduc holdem different from all the texas holdems?

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#104]
The texas holdem and texas holdem no limit  reward structure is:

| Winner            | Loser              |
| :------------: | ------------- |
| +raised chips | -raised chips |

Yet for leduc holdem it's:

| Winner               | Loser                  |
| :--------------: | --------------- |
| +raised chips/2 | -raised chips/2 |

Surely this is a bug?

**Comment by justinkterry** [comment]
@lssr

**Comment by daochenzha** [comment]
I think Leduc should be raised chips and Limit Hold'em is raised chips/2. The reward of Texas Hold'em is calculated by winning chips / big blinds (big blinds is 2). For Leduc Hodem, our version does not consider small and big blinds. We instead consider both players put 1 chip at the beginning.

**Comment by justinkterry** [comment]
Right now, leduc is raised chips/2. Texas hold'em and limit hold'em are raised chips. Are you saying that limit holdem should be raised chips/2 instead?

Additionally, isn't that not the full version of leduc hold'em then?

**Comment by daochenzha** [comment]
I have double-checked the implementations.  Leduc uses raised chips, and Texas hold'em uses raised chips/2. Am I missing something? I am not sure why we got different observations.

Thanks for pointing out. We will fix this issue of Leduc to make it compatible with Texas Hold'em.

**Comment by justinkterry** [comment]
Any updates on this?

**Comment by ruzhwei** [comment]
Hello, we have made Leduc compatible with Texas Hold'em. Now it has small/ big blinds and a reward of chips/big blinds.

**Comment by justinkterry** [comment]
Are the fixes for that released to PyPI?

**Comment by hsywhu** [comment]
@justinkterry Hi, the newest version 0.1.14 is uploaded to PyPI.
