### ISSUE TITLE
empty episodes in leduc hold'em

### ISSUE THREAD

**Issue by xaviervalette** [datamllab/rlcard#105]
This code gives me an empty episode 2. What does that mean? 

    ''' An example of playing Leduc Hold'em with random agents
    '''

    import rlcard
    from rlcard.agents.random_agent import RandomAgent
    from rlcard.utils.utils import *

    # Make environment
    env = rlcard.make('leduc-holdem')
    episode_num = 10
    # Set a global seed
    set_global_seed(0)

    # Set up agents
    agent = RandomAgent(action_num=env.action_num)
    env.set_agents([agent, agent])

    for episode in range(episode_num):

        # Generate data from the environment
        trajectories, _ = env.run(is_training=False)

        # Print out the trajectories
        print('\nEpisode {}'.format(episode))
        for ts in trajectories[0]:
            print('State: {}, Action: {}, Reward: {}, Next State: {}, Done: {}'.format(ts[0], ts[1], ts[2], ts[3], ts[4]))

**Comment by daochenzha** [comment]
@xaviervalette It may be because player 1 is the second to play and the other player folds in the first round. So there is no episode for player 1.
