### ISSUE TITLE
Tensorflow syntax is for tfv1, consider upgrading to tfv2

### ISSUE THREAD

**Issue by jinnyyan** [datamllab/rlcard#109]
Consider using Tensorflow's automatic upgrade ability to update tfv1 syntax to tfv2.

Source: https://www.tensorflow.org/guide/upgrade

**Comment by daochenzha** [comment]
@jinnyyan Thanks for letting us know! We will work on upgrading.

**Comment by weiwenwang** [comment]
we need tfv2 too.
i'm developer, working for bianfeng which is a chess and card game company in hangzhou China

**Comment by daochenzha** [comment]
Currently we only support torch
