### ISSUE TITLE
Leduc Holdem Observation Space

### ISSUE THREAD

**Issue by lssr** [datamllab/rlcard#110]
In v0.1.14, the observation space of Leduc Holdem was changed from an (34,) array to a (49,) array but the documentation was not updated. It looks like  the new observation space array now includes 15 zeros at the end. Could you describe what the new observation space encodes?

@justinkterry

**Comment by daochenzha** [comment]
@lssr Thanks for reporting. It is mainly caused by supporting big blinds in https://github.com/datamllab/rlcard/issues/104 More bits are used to represent the chips for each player. Maybe @ruzhwei could give a better explanation.

**Comment by ruzhwei** [comment]
Thanks for pointing out. 49 is larger than required because I misunderstood the state encoding when adding big blinds support. I have corrected it and updated the documentation. Sorry about this confusion.

**Comment by justinkterry** [comment]
Is the fix released on PyPI?

**Comment by hsywhu** [comment]
@lssr @justinkterry The fix is released on PyPI now in version 0.1.15. We will update the documents for leduc holdem on our official website later.
