### ISSUE TITLE
How can load model with trained Nolimitholdem?

### ISSUE THREAD

**Issue by ericntunctu** [datamllab/rlcard#112]
Hi, I have already trained a model by running nolimit_holdem_dqn.py in the example.
It produces a model file called nolimit_holdem_dqn.
However, when I tried to test the model:
##
env = rlcard.make('no-limit-holdem', config={'record_action': True})
human_agent = HumanAgent(env.action_num)
models.load('models/nolimit_holdem_dqn') 
##
It can not work (change loading file to any subfile also not work)
Can you help me to figure out it?

Also, I have seen the env for the Nolimitholdem. Can I just change self.num_players to be >2 and then I can train single agents or multi-agents for multiplayer Nolimitholdem?

**Although I know that you do not have a GUI for Nolimitholdem. But can I control cards agents get and then see what agents will do in different circumstances? since I want to know the agent's strategy for various post-flop. So I need to know what hand agent has and control the board.**

Thanks for your help

**Comment by daochenzha** [comment]
@ericntunctu Take NFSP on Leduc as an example, the model loading currently works as follows:

1. Put the trained models in https://github.com/datamllab/rlcard/tree/master/rlcard/models/pretrained/leduc_holdem_nfsp
2. Implement a model loader as in https://github.com/datamllab/rlcard/blob/master/rlcard/models/pretrained_models.py#L13
3. Register the model here https://github.com/datamllab/rlcard/blob/master/rlcard/models/__init__.py#L12
4. Load the model using `model = models.load('leduc-holdem-nfsp')` and use `model.agents` to obtain the trained agents in all the seats.

The process may be not that straightforward. We may replace it with a better one when we have time to do so.

Yes, self.num_players can be modified. 

You may be able to do so by handcrafting the state in https://github.com/datamllab/rlcard/blob/master/rlcard/envs/nolimitholdem.py#L34
