### ISSUE TITLE
Setting  RNG seeds

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#113]
Gym lets you set RNG seeds at the start of an environment in order to make play-throughs of an environment reproducible. How can this be done with RLcard? This would solve a problem I'm having.

**Comment by daochenzha** [comment]
@justinkterry We seed all the used modules such as random, NumPy and Tensorflow to make sure it generates the same result with the same seed.  See https://github.com/datamllab/rlcard/blob/master/rlcard/utils/utils.py#L316

**Comment by justinkterry** [comment]
You might want to clarify this in the documentation
