### ISSUE TITLE
Environment-local RNG seeds/state

### ISSUE THREAD

**Issue by weepingwillowben** [datamllab/rlcard#125]
I am working with @justinkterry and we want seeded environments that are not dependent on the np.random or random module's global state for maximal reproducibility. We are not concerned about the agents. 

The problem is that if a user is using the environments directly, then calls to np.random or random outside the environment will change the behavior of the environment, since these modules rely on a global RNG state. Instead we would like every environment to be independent from other user code.

Looking through the code, it looks like it would involve:

1. Adding seed argument to environments.
1. A test for each environment that checks that the environments are not dependent on global useage of np.random or random modules. 
1. Creating an np.random.RandomState with the appropate seed in each environment
1. Passing this random state object from the environment to the game and dealer classes
1. Converting all useage of np.random and random modules in the game and dealer classes to use this random object

Is this reasonable? I could make a PR with the second step if that is the hardest part.

**Comment by daochenzha** [comment]
@weepingwillowben Looks pretty nice. Thanks for the suggestion. We will be working on the dev branch to make this modification. It would be appreciated if you could help us in the second step.

**Comment by justinkterry** [comment]
I'll add one point of clarification:

Running multiple instances of one RL environment on a single computer is common and important. The globalness your RNG seeding makes doing that super problematic, which makes this a much bigger issue than it seems like at first.

**Comment by daochenzha** [comment]
@justinkterry Thanks for posting. Your clarification makes lots of sense. We will be working on it.

**Comment by weepingwillowben** [comment]
I will note that Gym has this feature, so it also has some utilities that are very helpful. For step 3., Gym has a utility you can call with 
```
from gym.utils import seeding
np_random, seed = seeding.np_random(seed)
```

This utity takes care of all the absurd issues that tend to arrise when creating np.random.RandomState objects.

**Comment by daochenzha** [comment]
@weepingwillowben Hi, I have just seed all the environments as you suggested. See dev branch https://github.com/datamllab/rlcard/tree/dev I have done some initial tests, and they look fine. But I am not sure whether there is any bug. Maybe you have done similar tests in your package. If so, could you help me the test is systematical? Thanks.

**Comment by weepingwillowben** [comment]
Looks good. I'll close this issue now.
