### ISSUE TITLE
Possible coding error for predict method in dqn_agent ?

### ISSUE THREAD

**Issue by billh0420** [datamllab/rlcard#127]
It seems to me that the predict method in dqn_agent might take an invalid action as the best action.

The problem shows up as a sudden sharp drop in reward learning. With the changes below, these drops still occur (maybe indicating there are still problems remaining), but the drops are fewer.

Here are my revised changes to the "predict" method and the "step" method in dqn_agent (note that the step method is not wrong, but I wanted to pass the 'state' rather than just the observation of the state to the predict method):

    def predict(self, state):  # FIXED: 200427
        ''' Predict the action probabilities

        Args:
            state: current state

        Returns:
            q_values (numpy.array): a 1-d array where each entry represents a Q value
        '''
        obs = state['obs']
        legal_actions = state['legal_actions']
        epsilon = self.epsilons[min(self.total_t, self.epsilon_decay_steps-1)]
        A = np.ones(self.action_num, dtype=float) * epsilon / len(legal_actions)
        q_values = self.q_estimator.predict(self.sess, np.expand_dims(obs, 0))[0]
        for action in range(self.action_num):
            if action not in legal_actions:
                q_values[action] = -np.inf
                A[action] = 0
        best_action = np.argmax(q_values)
        A[best_action] += (1.0 - epsilon)
        return A

    def step(self, state):  # FIXED: 200427
        ''' Predict the action for generating training data

        Args:
            state: current state

        Returns:
            action (int): an action id
        '''
        A = self.predict(state)
        A = remove_illegal(A, state['legal_actions'])
        action = np.random.choice(np.arange(len(A)), p=A)
        return action

**Comment by daochenzha** [comment]
@billh0420 Thanks for reporting. You are right putting the removing illegal part in predict would be better. But I suggest to use the remove illegal function instead. It could be faster than the for loop. And also remove the remove illegal in step which is redundant.
