### ISSUE TITLE
Leduc NFSP reward doesn't increase during training

### ISSUE THREAD

**Issue by aaronharsh** [datamllab/rlcard#134]
The "NFSP on Leduc Holdem" chart in https://towardsdatascience.com/rlcard-building-your-own-poker-ai-in-3-steps-398aa864a0db shows  the agent quickly reaching a reward of ~2.0 within 50,000 timesteps.

The output of python examples/leduc_holdem_nfsp.py on my system never shows a reward above 1.15, even after 40,000,000 timesteps:

![image](https://user-images.githubusercontent.com/1312241/80850842-0109c800-8bd3-11ea-887a-a05c6040d223.png)

Is that expected?  Should I use a different training command?

I'm using rlcard cloned from github, with this commit:

```
commit 60f1410f2ef443ac81be639fc880c7f7f37eca64 (HEAD -> master, origin/master, origin/dev, origin/HEAD)
Author: Songyi Huang <songyih1996@gmail.com>
Date:   Fri Apr 24 11:36:10 2020 -0700

    update version num
```

My system is running OS X Catalina.  I get the same results with homebrew python 3.7 and Conda python 3.5.

**Comment by daochenzha** [comment]
@aaronharsh Hi, thanks for posting. It is expected. A possible explanation is that we have changed the calculation of reward. Originally, it is winning chips. Now it is winning chips / big blind. Here, big blind = 2. Thus the result is comparable if you multiply it with 2.

See https://github.com/datamllab/rlcard/issues/104 

There are also changes in state space and network structure. So other hyperparameters could perform better.

**Comment by aaronharsh** [comment]
Thanks for the quick response, Zha!  That makes perfect sense.
