### ISSUE TITLE
Leduc holdem human example is not working

### ISSUE THREAD

**Issue by MihanixA** [datamllab/rlcard#136]
This happens if you run the script:
```(venv) mihanix-it@mihanix-it-OSX poker % python script.py 
>> Leduc Hold'em pre-trained model
>> Start a new game
Traceback (most recent call last):
  File "script.py", line 24, in <module>
    final_state = trajectories[0][-1][-2]
IndexError: list index out of range```

**Comment by daochenzha** [comment]
@MihanixA Thanks for reporting. Could you provide more information so that we can better check it? What is `scrip.py` that you are running? And what Python version did you use? Thanks.

**Comment by MihanixA** [comment]
`script.py` is a copy of `examples/leduc_holdem_human.py`
Initially I thought that this package would be available by pip so I copied just this file instead of the repository.

**Comment by daochenzha** [comment]
@MihanixA I can not reproduce this error from my side. So my best guess is that the problem is caused by the python version. Could you let me know your Python version so that I could better reproduce the error? Thanks.

**Comment by MihanixA** [comment]
My Python version is 3.7.5. Thank you in advance!

**Comment by daochenzha** [comment]
@MihanixA I am still not able to reproduce the error. with Python 3.7. Based on your error, there must be something wrong in the `trajectories`. Could you let me know what is the value of the trajectories?

**Comment by MihanixA** [comment]
I am a little bit high and want to play some console poker.
