### ISSUE TITLE
Multiple agents for Non-limit Holdem (more than 2)

### ISSUE THREAD

**Issue by brucefeynman** [datamllab/rlcard#140]
Hi, I am interested in your project especially Non-limit Holdem. It has been years since I learned ML in college, so I am kind of an infant in this new field.

I have read your code and the NFSP example on nonlimit holdem. From your game interface,  it is possible to add more than 2 players. But how am I going to evaluate it?

**Comment by daochenzha** [comment]
@brucefeynman Hi, thanks for your interest. We currently do not support explicit interfaces for changing the number of players. But you can achieve this by simply changing a configuration of the game in https://github.com/datamllab/rlcard/blob/master/rlcard/games/nolimitholdem/game.py#L37

To evaluate the performance, you may use the function defines in 
https://github.com/datamllab/rlcard/blob/master/rlcard/utils/utils.py#L374

**Comment by brucefeynman** [comment]
Thanks for the quick reply.

I have observed the player number as described there https://github.com/datamllab/rlcard/blob/master/rlcard/games/nolimitholdem/game.py#L37
and change it to 6 https://github.com/datamllab/rlcard/blob/0139d0e403b6d844a8f9107237887d73c7e8d752/rlcard/games/nolimitholdem/game.py#L26
When evaluating, I add 5 random players to run with one of the agents.
`eval_env.set_agents([agents[0], random_agent,random_agent,random_agent,random_agent,random_agent])`

But when I try your example code https://github.com/datamllab/rlcard/blob/master/examples/nolimit_holdem_nfsp.py
An error occurred in https://github.com/datamllab/rlcard/blob/0139d0e403b6d844a8f9107237887d73c7e8d752/rlcard/games/limitholdem/judger.py#L38 as the sum of winners is 0.

So I use debugger to trace the stack and find out that in some situations, compare_hands will produce wrong result.
https://github.com/datamllab/rlcard/blob/0139d0e403b6d844a8f9107237887d73c7e8d752/rlcard/games/limitholdem/judger.py#L31

The error case is `hands = [['C5', 'S9', 'S6', 'C2', 'CT', 'C7', 'H5'], ['S7', 'SJ', 'S6', 'C2', 'CT', 'C7', 'H5'], None, None, ['H7', 'DJ', 'S6', 'C2', 'CT', 'C7', 'H5'], None]`

The correct result for `winners` should be [0,1,0,0,1,0] since player 1 and 4 both have a pair of 7, but instead, the return value is [0,0,0,0,0,0]

I also tested compare_hands function with the same input and error still occurs.

Any idea on how to fix it?

**Comment by daochenzha** [comment]
@brucefeynman Thanks for reporting. It looks like a bug. We have not well tested the situations when player_num>2. We will fix this issue and let you know

**Comment by ruzhwei** [comment]
@brucefeynman  Thanks for pointing out. I have fixed this bug, and now it should be OK.

**Comment by brucefeynman** [comment]
Cool. Thanks for the quick fix! @ruzhwei
