### ISSUE TITLE
Importing rllcard is slow

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#142]
Running `import rlcard` is very slow compared to most packages. Can you please fix this?

**Comment by justinkterry** [comment]
@daochenzha

**Comment by daochenzha** [comment]
@justinkterry Thanks. I will check this issue.

**Comment by hsywhu** [comment]
@justinkterry hi, we've uploaded a new version 0.2.4 to PyPI. Now import should be much faster.
