### ISSUE TITLE
PettingZoo

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#143]
@daochenzha 

This is what we've been working on this whole time:
https://github.com/PettingZoo-Team/PettingZoo

It's essentially a multi-agent version of Gym, including a tremendous number of environments and the ones from RL card (under classic). We're trying to do a full release in the next month or so, but it's working and everything now.

**Comment by daochenzha** [comment]
@justinkterry Thanks for sharing. There are indeed tremendous number of environments. I would love to have a try when it is released.

**Comment by justinkterry** [comment]
@daochenzha Everything's fully working and it should be completely released sometime this week.

**Comment by daochenzha** [comment]
@justinkterry Sounds great. I will stay tuned.

**Comment by justinkterry** [comment]
1.0 is now out
