### ISSUE TITLE
Doesn't Doudizhu state need to know if current player is landlord or not?

### ISSUE THREAD

**Issue by billh0420** [datamllab/rlcard#146]
Shouldn't the state of Doudizhu have an indicator whether current player is landlord or not?

For example, a defender may not overtake his co-defender trick many times while the landlord would usually attempt to win the trick in order to lead.

**Comment by daochenzha** [comment]
@billh0420 Currently the three players are in a fixed sequence, i.e., the first player is always the landlord, and the second and third players are always peasants. Thus, the first agent will only learn how to play as landlord, and the other two will only learn how to play peasants.

**Comment by billh0420** [comment]
Doesn't this mean that I need to create two models (one for a landlord, second for peasant)?

**Comment by daochenzha** [comment]
@billh0420 Yes it is. I expect this is a reasonable choice, since each player may play with a significantly different strategy in Dou Dizhu. Of course, you may change the state space if you would like to have one agent for all the roles.
