### ISSUE TITLE
Difference in doudizhu between source code and documents

### ISSUE THREAD

**Issue by fecet** [datamllab/rlcard#157]
The documents say `The size of the action space of Dou Dizhu is 33676.` But the json file in `games/doudizhu/jsondata/card_type.json` only contains 27471, more detail:

trio_solo_chain_5    10388
trio_solo_chain_4     7184
trio_solo_chain_3     3282
four_two_solo         1326
trio_pair_chain_3     1200
trio_pair_chain_4     1134
trio_solo_chain_2      968
four_two_pair          858
trio_pair_chain_2      605
trio_solo              182
trio_pair              156
solo                    15
pair                    13
trio                    13
bomb                    13
trio_chain_2            11
trio_chain_3            10
pair_chain_3            10
pair_chain_4             9
trio_chain_4             9
trio_chain_5             8
pair_chain_5             8
solo_chain_5             8
pair_chain_6             7
trio_chain_6             7
solo_chain_6             7
solo_chain_7             6
pair_chain_7             6
pair_chain_8             5
solo_chain_8             5
solo_chain_9             4
pair_chain_9             4
pair_chain_10            3
solo_chain_10            3
solo_chain_11            2
rocket                   1
solo_chain_12            1

seems there is something wrong in plane case.

**Comment by CaoYuanpu** [comment]
@fecet  Thanks for letting us know. I have updated the actions in documents. Now the size of the action space of Dou Dizhu is 27472 with a **"pass"** action which is not in json file.

**Comment by fecet** [comment]
> @fecet Thanks for letting us know. I have updated the actions in documents. Now the size of the action space of Dou Dizhu is 27472 with a **"pass"** action which is not in json file.

But this is still less than 33676 mentioned in [documents](http://rlcard.org/games.html#dou-dizhu)

Type | Number of Actions | Number of Actions after Abstraction | Action ID
-- | -- | -- | --
Solo | 15 | 15 | 0-14
pair | 13 | 13 | 15-27
Trio | 13 | 13 | 28-40
Trio with single | 182 | 13 | 41-53
Trio with pair | 156 | 13 | 54-66
Chain of solo | 36 | 36 | 67-102
Chain of pair | 52 | 52 | 103-154
Chain of trio | 45 | 45 | 155-199
Plane with solo | 24721 | 38 | 200-237
Plane with pair | 6552 | 30 | 238-267
Quad with solo | 1339 | 13 | 268-280
Quad with pair | 1014 | 13 | 281-293
Bomb | 13 | 13 | 294-306
Rocket | 1 | 1 | 307
Pass | 1 | 1 | 308
Total | 33676 | 309

**Comment by CaoYuanpu** [comment]
@fecet  The documents(https://github.com/datamllab/rlcard/blob/master/docs/games.md#dou-dizhu) in github have been updated, and we will soon update the documents in http://rlcard.org/games.html#dou-dizhu
| Type             | Number of Actions | Number of Actions after Abstraction | Action ID         |
| ---------------- | :---------------: | :---------------------------------: | :---------------: |
| Solo             |        15         |        15                           | 0-14              |
| pair             |        13         |        13                           | 15-27             |
| Trio             |        13         |        13                           | 28-40             |
| Trio with single |        182        |        13                           | 41-53             |
| Trio with pair   |        156        |        13                           | 54-66             |
| Chain of solo    |       36          |        36                           | 67-102            |
| Chain of pair    |       52          |        52                           | 103-154           |
| Chain of trio    |        45         |        45                           | 155-199           |
| Plane with solo  |        21822      |        38                           | 200-237           |
| Plane with pair  |        2939       |        30                           | 238-267           |
| Quad with solo   |       1326        |        13                           | 268-280           |
| Quad with pair   |       858        |        13                           | 281-293           |
| Bomb             |        13         |        13                           | 294-306           |
| Rocket           |         1         |         1                           | 307               |
| Pass             |         1         |         1                           | 308               |
| Total            |       27472       |        309                          |                   |

**Comment by hsywhu** [comment]
Related docs on the official website have been updated. http://rlcard.org/games.html#action-abstraction-of-dou-dizhu
