### ISSUE TITLE
why is the performance of deep cfr not better than nfsp on limit-holdem

### ISSUE THREAD

**Issue by Simiw** [datamllab/rlcard#163]
I see the experimental results in the paper, the performance of deep cfr will be better. I tested these two algorithms, the performance of deep cfr is actually not good.

**Comment by daochenzha** [comment]
@Simiw We have tried our best to check the implementation and tried many hyperparameters, but it still does not work well. I expect more efforts in tuning/debugging may be needed in order to achieve the performance.

**Comment by Simiw** [comment]
@daochenzha I found that your implementation is a little different from the paper. The network in the paper uses two separate branches as input, while your implementation has only one branch. The depth of the layer is also different. Do you think these may affect performance? I might try these.

**Comment by daochenzha** [comment]
@Simiw yes it is possible. It is deep learning so the network architecture matters.

**Comment by Simiw** [comment]
@daochenzha ok, I will continue to try more of this.
