### ISSUE TITLE
Future maintenance of RLCard

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#167]
Given the scope of our PettingZoo library, it's something we plan to maintain for a _very_ long time.

Typically, not too long after an RL library gets a paper accepted, the library stops being maintained. We've fixed up and are now maintaining a bunch of RL libraries (in most cases officially)- MPE, MAgent, Gym-Checkers, Gym-Backgammon, the SISL environments, and we've made a bunch of contributions to ALE. 

If you get to the point where you no longer want to maintain RLCard, we'd be happy to take over.

**Comment by daochenzha** [comment]
@justinkterry Thanks for the proposal. We will keep maintaining RLCard in the near future. I will let you know if we get to that point.
