### ISSUE TITLE
mahjong_dqn

### ISSUE THREAD

**Issue by chenzhenfeng-stack** [datamllab/rlcard#169]
In the Mahjong game dqn, I added 3 real agents, then started the game and trained 100,000 times, but the winning rate did not improve. What could be the reason?
![fig](https://user-images.githubusercontent.com/35213129/93415615-823dcf00-f8d6-11ea-9048-f75d1b8c42d2.png)

**Comment by daochenzha** [comment]
@chenzhenfeng-stack DQN may not work well for Mahjong (or need tuning hyperparameters). Policy gradient methods could work better.

**Comment by chenzhenfeng-stack** [comment]
> @chenzhenfeng-stack DQN may not work well for Mahjong (or need tuning hyperparameters). Policy gradient methods could work better.

Thanks, any good suggestions for parameter adjustment

**Comment by daochenzha** [comment]
@chenzhenfeng-stack I would suggest trying PPO or other policy gradient methods. They could be more suitable for Mahjong than DQN. See Microsoft Mahjong paper. https://arxiv.org/abs/2003.13590
