### ISSUE TITLE
关于No limit Texas Hold'em 中 trajectories 的'obs'

### ISSUE THREAD

**Issue by ray-chien** [datamllab/rlcard#170]
您好，最近在练习这个项目
我在 game.py 中将 NolimitholdemGame 的 num_player 改成 6（期望是6位玩家）。
trajectories 中的 'obs'，就我理解应该是RL领域中所谓的observation or state。
原先 2 players 时，'obs' 共为54项
若理解没错，应为下图所示
![image](https://user-images.githubusercontent.com/65266065/94647988-30f4fd00-0324-11eb-9883-6c59f1921869.png)
所以 6 players 时栏位预期会增加，但实际上仍然是54项。
请问是理解上有误还是？
谢谢！

**Comment by daochenzha** [comment]
@raychien1123 Nolimitholdem是非完全信息游戏，所以目前的设定是不管有几个player，observation都是自己看到的牌。如果想更改这个设定，可以修改https://github.com/datamllab/rlcard/blob/master/rlcard/envs/nolimitholdem.py#L37
