### ISSUE TITLE
dqn+mcts

### ISSUE THREAD

**Issue by Cristal-yin** [datamllab/rlcard#172]
你好，最近怎么没更新了，想问问dpn+mcts是否可行呢，最近在看这个但是代码上无从下手，您有什么好的建议吗

**Comment by daochenzha** [comment]
@Cristal-yin 这个应该是可行的，不过确实很难下手。首先DQN因为有buffer所以可能训练速度难以保证，其次mcts本身可能会很慢。我的建议是像deltadou那样用policy value network https://www.ijcai.org/Proceedings/2019/0176.pdf 或者用一些其他不需要buffer的方法。

我们这边也在研究斗地主AI算法，有进展会继续更新。

**Comment by Cristal-yin** [comment]
我毕设打算做这个方面的，已经开题不能回头😹，不知道方不方便加个微信🤦‍♀️

**Comment by Cristal-yin** [comment]
yth3365278
