### ISSUE TITLE
Cuda training with Pytorch

### ISSUE THREAD

**Issue by KristofJuhasz96** [datamllab/rlcard#174]
Hey,

I was trying out your NFSP with Cuda GPU and Pytorch. I was following this example: https://github.com/datamllab/rlcard/blob/master/examples/leduc_holdem_nfsp_pytorch.py

When setting the device to "cuda" I get the following error:

~/projects/rl-learning/venv/lib/python3.7/site-packages/rlcard/agents/nfsp_agent_pytorch.py in _act(self, info_state)
    228 
    229         with torch.no_grad():
--> 230             log_action_probs = self.policy_network(info_state).numpy()
    231 
    232         action_probs = np.exp(log_action_probs)[0]

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

As the Error suggest, this issue could be solved by first converting the Tensor (if cuda is used).

**Comment by daochenzha** [comment]
@KristofJuhasz96 Thanks for letting us know. I have fixed this bug in the latest commit.
