### ISSUE TITLE
Running best response agent with limit-hold'em game got runtime error

### ISSUE THREAD

**Issue by zzzyoung** [datamllab/rlcard#175]
I adapted one of the example script "leduc_holdem_br" to a limit-hold'em version by replacing the game config from leduc hold'em to limit hold'em.  TypeError occurred in runtime where the action returned by the best response agent was an empty string.
During debug process, the variable 'infoset' in function 'best_response_action' in 'best_response_agent.py' was an empty list, such that the loop for picking best response action was not entered.

By the way could you please provide some example code when using best response agent play against newly trained RL agent?

**Comment by daochenzha** [comment]
@zzzyoung The best response implementation has some issues that we have figured out yet. We will be working on this. Sorry for the inconvenience.

**Comment by zzzyoung** [comment]
> @zzzyoung The best response implementation has some issues that we have not figured out yet. We will be working on this. Sorry for the inconvenience.

Thank you for the reply. I am looking forward to the update.
