### ISSUE TITLE
DeepCFR无法进行多进程加速

### ISSUE THREAD

**Issue by ChloroplastYu** [datamllab/rlcard#182]
如题，在env_num参数大于1时，DeepCFR无法运行。

deep_cfr_agent在初始化时需要使用_env.reset()函数以获取init_state，然而在vec_env中并没有reset()的实现。

请问DeepCFR无法使用多进程进行加速嘛？如果能够使用多进程的话我应该怎样修改源码呢？

十分感谢！！

**Comment by daochenzha** [comment]
@ChloroplastYu DeepCFR目前不支持多进程。因为DeepCFR要对游戏树展开，多进程不容易实现

**Comment by ChloroplastYu** [comment]
好吧，非常感谢您的及时回复。
