### ISSUE TITLE
Should Action.FOLD always been 0 in NL holdem?

### ISSUE THREAD

**Issue by aetheryang** [datamllab/rlcard#183]
**As log say:**
>> Player 1 chooses Action.ALL_IN
=============== Community Card ===============
=============  Player 0 - Hand   =============
===============     Chips      ===============
In Pot: 134
Remaining: [66, 0]
=========== Actions You Can Choose ===========
0: Action.CALL, 1: Action.FOLD

**BUT when some one just raise or call:**
>> Player 1 chooses Action.RAISE_HALF_POT
=============== Community Card ===============
=============  Player 0 - Hand   =============
===============     Chips      ===============
In Pot: 24
Remaining: [90, 86]
=========== Actions You Can Choose ===========
0: Action.FOLD, 1: Action.CALL, 2: Action.RAISE_HALF_POT, 3: Action.RAISE_POT, 4: Action.ALL_IN

**Comment by aetheryang** [comment]
补充说明：具体情况是这样的，我在 NL 德州的 human 2人桌下玩了几把，发现当一方 all in 时，另一方可操作的选项只有 FOLD 和 CALL，但 CALL 对应了0， FOLD 对应了1. 而普通的下注加注时 FOLD 是 0，CALL 是 1.

**Comment by daochenzha** [comment]
@aetheryang The id here is just an ID to make the selection easier. It does not correspond to the action in the environment.

**Comment by alexx-ftw** [comment]
Should this be closed?

**Comment by daochenzha** [comment]
@alexx-ftw Yes I will close it. Thanks!
