### ISSUE TITLE
请问有打算加入新的牌类游戏吗？

### ISSUE THREAD

**Issue by lbyczzz** [datamllab/rlcard#184]
您好，很感谢您提供的非完全信息牌类游戏环境。
但是我发现一个比较重要的问题，就是这些游戏本质上除了信息不对称外，其它的几乎都是对称的，它们的前提都是对称博弈，即每个智能体是可以互相替换的，它们有完全相同的策略集合。有一类牌类游戏是非对称博弈的，例如游戏中有庄一人，多名闲家(不同于斗地主)， 闲家之间是独立的，没有协作博弈，庄家按顺序对闲家采取策略，闲家依照庄家的对自己采取的动作而采取策略。
请问，此类游戏的环境后续会添加吗？谢谢。

**Comment by daochenzha** [comment]
@lbyczzz 斗地主为什么不是非对称的呢？斗地主里智能体显然是不能互换的？对于您说的新的环境，可以举一些例子吗？

**Comment by lbyczzz** [comment]
您说的确实很对，可能是我描述的不是很好，我说的是那种玩家之间的动作集和信息集都不一样的，国内有款叫做"水鱼"的棋牌游戏很符合我这类例子

**Comment by daochenzha** [comment]
您好，我搜索了一下没有找到“水鱼”游戏，只找到一些水鱼的游戏app。可以发一些介绍“水鱼”的链接吗？不知道到“水鱼”的受众怎么样

**Comment by lbyczzz** [comment]
https://wenku.baidu.com/view/137293413868011ca300a6c30c2259010202f3e6.html  这是介绍该游戏规则的，受众的话不是很多，但是可以作为一种典型的非对称对抗博弈的研究对象，还是很不错的

**Comment by daochenzha** [comment]
@lbyczzz I have briefly surveyed this game. It is indeed interesting but it seems like not many people are playing it. I will hold this issue for while to see whether anyone interested would like to contribute to the implementation of this game.

**Comment by lbyczzz** [comment]
Thank you for your attention
