### ISSUE TITLE
bad performance for policy gradient algorithm on nolimit_holdem game

### ISSUE THREAD

**Issue by xiliu** [datamllab/rlcard#186]
In order to express accurately, I will use Chinese to describe my problem

首先，非常感谢分享这个项目！！

我使用policy gradient的方法训练nolimit_holdem游戏。也尝试过包括reward归一化、不同gamma损失因子、更新网络参数后清空memory并重新生成一批数据。结果都不好，训练结果如下图
![image](https://user-images.githubusercontent.com/7224986/99931926-58e76680-2d91-11eb-885b-042a66807bed.png)

同样的网络、环境配置下，训练你们提供的demo（nolimit_holdem_dqn.py）则符合预期，如下图
![image](https://user-images.githubusercontent.com/7224986/99932023-b1b6ff00-2d91-11eb-9fb7-0e33abc2443d.png)

这个情况折磨我一周了，可能的问题原因会是什么？

再次感谢你们的项目分享！！！

**Comment by daochenzha** [comment]
@xiliu Thanks for the encouragement!

标准policy gradient的variance会很大，可能要仔细调参才可能稳定。可以尝试一些其他方法比如A2C或者PPO，它们通过value function来降低variance，可能更稳定

**Comment by xiliu** [comment]
@daochenzha 感谢你的回复和建议，我会尝试其他方法
