### ISSUE TITLE
Question on dqn_agent.py

### ISSUE THREAD

**Issue by billh0420** [datamllab/rlcard#188]
The following code appears in dqn_agent.py

```
        # Calculate q values and targets (Double DQN)
        q_values_next = self.q_estimator.predict(self.sess, next_state_batch)
        best_actions = np.argmax(q_values_next, axis=1)
        q_values_next_target = self.target_estimator.predict(self.sess, next_state_batch)
        target_batch = reward_batch + np.invert(done_batch).astype(np.float32) * \
            self.discount_factor * q_values_next_target[np.arange(self.batch_size), best_actions]
```

Why is best_actions computed using q_estimator rather than using target_estimator?
Also, shouldn't best_actions be named next_best_actions?

That is, why not do:

```
        # Calculate q values and targets (Double DQN)
        q_values_next_target = self.target_estimator.predict(self.sess, next_state_batch)
        next_best_actions = np.argmax(q_values_next_target, axis=1)
        target_batch = reward_batch + np.invert(done_batch).astype(np.float32) * \
            self.discount_factor * q_values_next_target[np.arange(self.batch_size), next_best_actions]
```

I still have stability issues with dqn_agent, but with the test example that I am working on, I get better results using the target_estimator rather than the q_estimator.

**Comment by daochenzha** [comment]
@billh0420 You are correct. The code you provide is the original DQN. The ones in our repo implement Double DQN in https://arxiv.org/pdf/1509.06461.pdf. Double DQN is shown to be more stable than DQN in many cases. I believe both are correct. It is possible that the original DQN performs better.
