### ISSUE TITLE
i can not find the model save code

### ISSUE THREAD

**Issue by sunnyForIOS** [datamllab/rlcard#19]
when i want to find how to save the agent model ,i can not find the model save code,but the pretrained model leduc_holdem_nfsp exsit. 
saver = tf.train.Saver(tf.model_variables())
saver.restore(self.sess, tf.train.latest_checkpoint(check_point_path))
so where is saver.save ?

**Comment by daochenzha** [comment]
Hello. Thank you for the feedback. It is a very good point. Indeed, the current examples do not include save code for brevity. An example of saving leduc_holdem_nfsp will be added to /examples shortly :)

**Comment by sunnyForIOS** [comment]
good, leduc_holdem_nfsp_save_model is added, thanks

**Comment by AhmedKhaled945** [comment]
Hello, i can't find this file, is it removed? if yes how can i save the model weights?

Thanks in advance.

**Comment by daochenzha** [comment]
@AhmedKhaled945 The code has been updated. The up-to-date version is as follows. Take Leduc Holdem NFSP as an example.

You can save model with
```
    # Save model
    save_dir = 'models/leduc_holdem_nfsp'
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
    saver = tf.train.Saver()
    saver.save(sess, os.path.join(save_dir, 'model'))
```
See https://github.com/datamllab/rlcard/blob/master/examples/leduc_holdem_nfsp.py#L88

To load the model, you can use (trained weights are provided in `models/pretrained/leduc_holdem_nfsp`. You can use your own instead)
```
# We have a pretrained model here. Change the path for your model.
check_point_path = os.path.join(rlcard.__path__[0], 'models/pretrained/leduc_holdem_nfsp')

with sess.as_default():
    with graph.as_default():
        saver = tf.train.Saver()
        saver.restore(sess, tf.train.latest_checkpoint(check_point_path))
```
See https://github.com/datamllab/rlcard/blob/master/examples/leduc_holdem_nfsp_load_model.py#L32
