### ISSUE TITLE
Multi-agent DQN and NFSP for no-limit-holdem

### ISSUE THREAD

**Issue by ryanakann** [datamllab/rlcard#190]
I've been scouring the documentation for an implementation of Multi-agent DQN and I haven't been able to find it. Anyone have any insights on how to do this properly? Looping and appending to a list of agents and passing into the environment doesn't seem to change the 'player_num' property of the environment, and directly setting that variable results in index out of bounds exceptions.

**Comment by ruzhwei** [comment]
Hello, I have made limitholdem and nolimitholdem support more players by pull request #191 . Take a look and let me know if you have any more questions.

**Comment by ryanakann** [comment]
> Hello, I have made limitholdem and nolimitholdem support more players by pull request #191 . Take a look and let me know if you have any more questions.

Much obliged!
