### ISSUE TITLE
setup.py cleanup

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#196]
So I've been going through the dependencies of packages PettingZoo depends on because the amount of dependencies has gotten massive, and I noticed a few things in your setup.py:

-packaging is depended on but isn't meaningfully used?
-pillow is a dependency but isn't used at all as far as I can tell
-matplotlib should be moved to be included in both extras, not by default. Without the learning functionality there's no use for it.

**Comment by daochenzha** [comment]
@justinkterry Thanks for pointing this out. We will double-check and remove them if they are not necessary.

**Comment by hsywhu** [comment]
@justinkterry Thanks, the dependencies are now cleaned as you suggested.

**Comment by justinkterry** [comment]
Thank you! can you please cut a new release to PyPI with this?

**Comment by hsywhu** [comment]
Yes, it has been released to PyPI
