### ISSUE TITLE
斗地主中状态表示无法区分另外两个人手牌

### ISSUE THREAD

**Issue by Michael1015198808** [datamllab/rlcard#198]
在斗地主中，每个Player得到的(6, 5, 15)的信息中仅编码了自己的手牌，其余两人的手牌的union，打过的牌，但是没有对另外两人剩下多少手牌进行编码。也即，地主在`other_hands`较少的时候，无法区分是两个人手牌都较少，还是一个人仅剩一张了。对农民而言，他无法区分是队友快逃完了还是地主快逃完了。这导致agent无法学习到很多策略（如农民帮队友逃牌，对手剩四五张时打单张，剩一张时打对子等等）

**Comment by daochenzha** [comment]
@Michael1015198808 没错，这个特征很关键。这个特者可以编码成20纬的one-hot表示，我们在正在更新斗地主环境，新版的环境会包含这个特征。目前RLCard里默认的强化学习算法较弱，我们近期会开源一个较强的斗地主AI（大约两到三个月后），会明显比规则强很多，这个特征也会用到。

**Comment by Michael1015198808** [comment]
我觉得不一定要用one-hot的方法表示。我觉得简单的在(6, 5, 15)之外再加入3×{1, 2, ..., 20}应该也可以做到。在不考虑过拟合的情况下，也并不需要对网路架构做过多更新。

其实这个问题是我们在你们代码基础上开发掼蛋（一个可以当成2V2的斗地主牌类游戏）的强化学习框架时发现的。我们发现我们训练得到的掼蛋机器人存在压队友的情况。后来发现很可能是因为它无法区分其它三家的牌。虽然我们编码时能让当前agent意识到出牌的是它队友，但是因为其他人手牌`others_hands`少在Function Approximator看来是比较不好的，所以它会“不由自主”地去压制其它任何人。

**Comment by daochenzha** [comment]
@Michael1015198808 谢谢分享。根据我们开发斗地主AI的经验，压制队友的问题可以通过显性编码队友特征缓解。比如斗地主中农民可以加入队友最近出的牌作为特征。在学习开始，农民会压制队友，但在后期（几天后）农民会学到与队友合作。

**Comment by lixiaozhui** [comment]
> 我们做的掼蛋里面有一个性质，就是队友一定是自己的上上家（因为是4人游戏，所以同时也是下下家）。所以因为状态中编码了前几手出的牌，所以也挺容易分辨出来的。
> 
> Anyway, 期待您的新工作！

请问可以分享一下掼蛋的强化学习框架嘛？
