### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by monkeycc** [datamllab/rlcard#199]
1  建议增加GPU版本
默认安装不是GPU版本，需要自己按照版本手动安装

建议

requirements.txt   requirements-gpu.txt

pip install rlcard[tensorflow]
pip install rlcard[tensorflow-gpu]
pip install rlcard[torch]
pip install rlcard[torch-gpu]

2. rlcard-showdown
设置之后，后台账户密码是？ 或者自己怎么设置

3.  斗地主只能训练地主吗，能不能训练农民

4. 能不能来个QQ交流群

**Comment by daochenzha** [comment]
@monkeycc 

1. 我们会在setup.py里加入gpu选项
2. https://github.com/datamllab/rlcard-showdown/issues/6
3. https://github.com/datamllab/rlcard/blob/master/examples/doudizhu_dqn.py#L48 在这里把agent放在第二或第三个位置就是农民。目前RLCard里默认的强化学习算法较弱，我们近期会开源一个强斗地主AI（大约两到三个月后），欢迎关注。
4. 我们会建群，请关注README。
