### ISSUE TITLE
Chips initialization in NL Holdem

### ISSUE THREAD

**Issue by aypee19** [datamllab/rlcard#200]
Hi, currently working on NL Holdem, I don't understand how we are supposed to init the chips number at the start of a game. In `init_game`, the chips are initialized like this:

`self.players = [Player(i, self.init_chips, self.np_random) for i in range(self.num_players)]`

Shouldn't it be possible to set the init chips of each players with the game `configure` method?

**Comment by ruzhwei** [comment]
Hello, I have added chips config by pull request#201. Check if this helps.

**Comment by aypee19** [comment]
Thanks, wasn't sure of how it should be done. We should also add blinds, and dealer designation if we want to have the possibility of simulating an entire game (until there is only one player left).

Actually the game doesn't work with more than 2 players, there are many flaws in the rules, so I'm working on all this and will soon make a pull request.
