### ISSUE TITLE
NFSP agent strategy

### ISSUE THREAD

**Issue by DoxakisCh** [datamllab/rlcard#204]
Hi!

I used the provided NFSP agent of your repo in your leduc and limit holdem environments. After a lot of training I decided to test them while I was also observing their strategy. I have noticed that that the agent's strategy was always the same in each of the game's stage (e.g. when the agent was playing first), regardless of the observations that the enviroment provided to it. Is this normal?

Thank you in advance!

**Comment by daochenzha** [comment]
@DoxakisCh It happens since the training neural networks can be unstable.. I would suggest trying different hyperparameters to see the results.
