### ISSUE TITLE
PettingZoo Link

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#205]
Hey, would you guys be okay with linking to pettingzoo in the readme (maybe in the news section)?

**Comment by daochenzha** [comment]
@justinkterry Added. It would be nice if you guys could also add a link to our project in your readme in case anyone is particularly interested in card games.

**Comment by justinkterry** [comment]
We link to RLCard in the documentation for all the environments that use RLCard, e.g. https://www.pettingzoo.ml/classic/dou_dizhu

**Comment by justinkterry** [comment]
Also thank you!
