### ISSUE TITLE
No module named 'tensorflow' when I was training nfsp_agent_pytorch

### ISSUE THREAD

**Issue by wbs306** [datamllab/rlcard#206]
This code https://github.com/datamllab/rlcard/blob/c6673c3b9bfc41461423d355febe4fded45fbede/rlcard/agents/dqn_agent_pytorch.py#L34 tried to import `Memory` from `dqn_gent` which is implemented with tensorflow, but I don't want to install tf. There is the same problem in this line: https://github.com/datamllab/rlcard/blob/c6673c3b9bfc41461423d355febe4fded45fbede/rlcard/agents/nfsp_agent_pytorch.py#L30
So I just copy the code of `Memory` and `ReservoirBuffer` to the files to avoid this problem, is there any better solution?

**Comment by daochenzha** [comment]
@wbs306 Thanks for pointing this out! This issue has been fixed.
