### ISSUE TITLE
DQN with Rule agent

### ISSUE THREAD

**Issue by 274927760** [datamllab/rlcard#208]
Hello, I used two random agents to train dqn(doudizhu) ，but the effect was not good, even far behind the rule agent. However,when I used two rule agents to train it,I found that during the training process (up to 50000 rounds), the reward remained around 0.2,How can I improve the training effect of dqn(doudizhu)?

**Comment by daochenzha** [comment]
@274927760 Yes, the provided DQN does not work well in DouDizhu. We are working on a much better algorithm. Please stay tuned.

**Comment by 274927760** [comment]
I'm looking forward to your work very much. By the way, can you provide a more appropriate algorithm or idea to build a doudizhu agent?

**Comment by 274927760** [comment]
Maybe there is something wrong with my expression. I only want to know if there are any good suggestions about trainning a doudizhu agent，because I want to finish my graduation thesis as soon as possible.I‘m looking forward to your suggestions.Thanks!

**Comment by daochenzha** [comment]
@274927760 There are two issues in the current DouDizhu. First, the abstraction is not good since currently the kicker is randomly selected. This can be improved. Second, some on-policy algorithms could work better and be more efficient.

**Comment by 274927760** [comment]
Thanks a bundle！I‘ll have a try!

**Comment by daochenzha** [comment]
A strong DouDizhu agent is at https://github.com/datamllab/rlcard/tree/master/rlcard/agents/dmc_agent

and

https://github.com/kwai/DouZero
