### ISSUE TITLE
关于cfr_agent代码实现的3点困惑

### ISSUE THREAD

**Issue by xiliu** [datamllab/rlcard#212]
您好，关于cfr_agent的代码实现有以下三点困惑，非常期待您的解答。谢谢
agents/cfr_agent.py
![image](https://user-images.githubusercontent.com/7224986/114664848-e02c7b00-9d2e-11eb-8f99-35849cb64471.png)
问题一：96行为什么要累加啊？不应该是这样吗？
self.regrets[obs][action] = regret
问题二：97行计算完全理解不了，该怎么理解？
问题三：如下图红框，为什么不用self.policy
![image](https://user-images.githubusercontent.com/7224986/114664891-efabc400-9d2e-11eb-9f21-2b9b59fdef59.png)

**Comment by daochenzha** [comment]
@xiliu 

问题一：regrets的计算是求和，可以参照Regret Minimization in Games with Incomplete Information的公式6
问题二：这里算的是平均的policy，这里用的是linear avaraging，就是对最近的权重更大
问题三：CFR里average的policy才会收敛，可以参照paper里的Theorem 2

**Comment by xiliu** [comment]
@daochenzha 感谢您的解答
