### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by xiliu** [datamllab/rlcard#214]
游戏在进行step_back()操作时，[这一步](https://github.com/datamllab/rlcard/blob/328175f5a81c3b67eb3882faa63f26db799fefc6/rlcard/games/nolimitholdem/game.py#L215)没有对self.stage进行step_back操作，导致[get_state](https://github.com/datamllab/rlcard/blob/328175f5a81c3b67eb3882faa63f26db799fefc6/rlcard/games/nolimitholdem/game.py#L188)时获得错误self.stage。

**Comment by ruzhwei** [comment]
I will take a look!

**Comment by justinkterry** [comment]
@ruzhwei @daochenzha Any progress on this? We're planning to start work on Poker soon

**Comment by ruzhwei** [comment]
Hi! Sorry for the long wait. I have fixed it and it should work correctly now.
