### ISSUE TITLE
python leduc_holdem_human.py next game error

### ISSUE THREAD

**Issue by simin75simin** [datamllab/rlcard#219]
OS: ubuntu 18.04
python version: 3.7.10

when i finished training leduc_holdem_human.py and ran ```python leduc_holdem_human.py```, the first game runs well. after that, i got the following error message:
```
Press any key to continue...
>> Start a new game
Traceback (most recent call last):
  File "leduc_holdem_human.py", line 24, in <module>
    final_state = trajectories[0][-1][-2]
IndexError: list index out of range
```

**Comment by daochenzha** [comment]
@simin75simin I didn't reproduce this error. Did you observe the same error when running the script again? I guess the problem should be that the opponent chooses to fold in the first round and the game ends without a final state of the human player.

**Comment by simin75simin** [comment]
yeah, i did not reproduce this error either. strange. perhaps it's a one time thing.
