### ISSUE TITLE
Documentation Problem for UNO

### ISSUE THREAD

**Issue by FranzPfeifroth** [datamllab/rlcard#220]
reference: https://rlcard.org/games.html#uno
Documentation says that the UNO game is encoded in 7 planes, each with dimension [4:15]
But  debugging the games shows just 4 planes as state after an env.reset()
Please explain me the current encoding of the state

**Comment by daochenzha** [comment]
@FranzPfeifroth Yes, thanks for pointing this out. It is 4 planes, where 3 of them are used to encode hand cards, and the last one is for the target card. We have removed the other three (which are originally for other's hand cards but should actually not be observable). We will update the document.

**Comment by daochenzha** [comment]
Document fixed
