### ISSUE TITLE
No num_players in Gin Rummy

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#225]
While gin rummy is a 2 player game and that shouldn't be changed, akin to Dou Dizhu only being a 3 player game, gin rummy still doesn't have the num_players argument the way all other rlcard environments have.

@kaanozdogru 
@daochenzha

**Comment by daochenzha** [comment]
@justinkterry  I have added the num_players. See https://github.com/datamllab/rlcard/commit/49a6613521e6c67c927fcaa4f883134f4b2a4bb4

Do you think it looks good? If so, we will update a PyPI version as well.

**Comment by justinkterry** [comment]
No PyPI release should be needed.

@kaanozdogru does that fix what you were complaining about to me earlier?
