### ISSUE TITLE
DQNAgent net is too simple?

### ISSUE THREAD

**Issue by sunnyForIOS** [datamllab/rlcard#24]
i notice that DQNAgent->_build_model has only two fc net , is it too simple?, and can not get better performance? why not use conv net ?

**Comment by daochenzha** [comment]
Good point! I agree that conv net may lead to better performance for some games, such as Dou Dizhu, where the features are represented as several planes. For some small games such as Blackjack and Leduc, I expect fc net would be enough to learn a good agent. Correct me if I am not right :) Actually, the current DQNAgent also allows specifying the number of layers and the dimension of each layer.

**Enhancement: the DQNAgent should support both fc net and conv net.** We will keep this in mind.

**Comment by sunnyForIOS** [comment]
one more thing，the model of doudizhu its model net input sharp is （6，5，15），if i use conv net，should i change the sharp to （5，15，6）

**Comment by sunnyForIOS** [comment]
like the format NWHC and NCWH？

**Comment by daochenzha** [comment]
Yes, the array should be transposed. You may use `tf.transpose` to achieve this. For the CNN filter size, I recommend trying 2d conv like 3 * 3, or 1d conv like 1 * 3.

BTW, I have updated the state encoding explanations of Dou Dizhu to make it more clear:
https://github.com/datamllab/rlcard/blob/master/docs/games.md#state-encoding-of-dou-dizhu

**Comment by sunnyForIOS** [comment]
if i want to add Kicker Net into doudizhi agent, can you give the some suggest?

**Comment by daochenzha** [comment]
@sunnyForIOS Kicker Net could be a good idea. However, It will increase the action space and make training difficult. Unfortunately, I do not have any suggestions for Kicker Net :)

**Comment by sunnyForIOS** [comment]
thanks，it is helpful

**Comment by sunnyForIOS** [comment]
it is very dejected, i add resnet18 in dqnangent net, when i train some epochs, loss  increase a lot and avg reward is less than 0.1
