### ISSUE TITLE
DQNAgent: Possible (typo/paste) error in method: feed(self, ts)

### ISSUE THREAD

**Issue by billh0420** [datamllab/rlcard#246]
Line 127 of method feed(self, ts) in DQNAgent.py is:

`
self.feed_memory(state['obs'], action, reward, next_state['obs'], list(state['legal_actions'].keys()), done)
`

It seems like it should be:

`
self.feed_memory(state['obs'], action, reward, next_state['obs'], list(next_state['legal_actions'].keys()), done)
`

**Comment by daochenzha** [comment]
@billh0420 Thanks for pointing out! I have just fixed it.
