### ISSUE TITLE
How to access the last game, please! Thank you!

### ISSUE THREAD

**Issue by jack86666** [datamllab/rlcard#25]

**Comment by daochenzha** [comment]
Hello, @jack86666 May I know what ‘last game’ refers to? Is it the previous game data or the last state of a game?

**Comment by jack86666** [comment]
I want to know How to access the previous game?

Daochen Zha <notifications@github.com> 于2019年11月9日周六 下午2:39写道：

**Comment by jack86666** [comment]
hi,sir How to take the next game and  It is the previous game data  ！thank
you！

dong xu <dongx803@gmail.com> 于2019年11月9日周六 下午4:47写道：

**Comment by daochenzha** [comment]
@jack86666 To start a new game, you can call `env.init_game()`. Then call `env.run()`, you will obtain the game data (trajectories) of one game and payoffs. Unfortunately, RLCard will not save the previous game data. If you want to access previous game data, you can simply store the trajectories into a list and access later. Thanks!

**Comment by jack86666** [comment]
Last question！I would like to know how to access the game of landlords in
progress!

Daochen Zha <notifications@github.com> 于2019年11月9日周六 下午10:31写道：

**Comment by daochenzha** [comment]
@jack86666 In this case, you may not use `env.run`. Instead, you may use `env.step` which will take one step, and return the next state and the next player. Then you can do whatever you want when the game is in progress.

See the definition of step: https://github.com/datamllab/rlcard/blob/b526e0e9fba0990e4a642ca03cf219c8e025d1c3/rlcard/envs/env.py#L46

You can also refer to the document to get a sense of the interface design:
https://github.com/datamllab/rlcard/blob/master/docs/high-level-design.md

**Comment by jack86666** [comment]
ok，Thank you very match!

Daochen Zha <notifications@github.com> 于2019年11月11日周一 上午11:20写道：

**Comment by jack86666** [comment]
hi,sir,The document or source code of  doudizhu‘s man-machine？I want Robot
Learning，Please！

Daochen Zha <notifications@github.com> 于2019年11月12日周二 上午1:01写道：

**Comment by daochenzha** [comment]
@jack86666 The action space of Dou Dizhu is too large, thus we have to make abstractions to make it feasible for RL algorithms. Although we have added some rules for kicker, the agent needs to learn how to make 309 decisions. This is still challenging.

**Comment by jack86666** [comment]
thks,Can provide a set of intelligent robot game to fight against
landlords,Please!

Daochen Zha <notifications@github.com> 于2019年11月13日周三 下午9:03写道：

**Comment by jack86666** [comment]
You only need to provide a set of source code for the doodler intelligent
robot game, and I will use it directly here, and I am willing to buy it

dong xu <dongx803@gmail.com> 于2019年11月15日周五 下午7:56写道：
