### ISSUE TITLE
Code correction for run_rl.py

### ISSUE THREAD

**Issue by billh0420** [datamllab/rlcard#253]
Lines 37-40 of run_rl.py are:

`         

            agents = [agent]

            for _ in range(env.num_players):

                    agents.append(RandomAgent(num_actions=env.num_actions))

             env.set_agents(agents)
`

There is an extra randomAgent being added.

A correction could be:

`          

            agents = [agent]

            for _ in range(1, env.num_players):

                    agents.append(RandomAgent(num_actions=env.num_actions))

            env.set_agents(agents)
`

**Comment by daochenzha** [comment]
Thanks for letting us know! It is fixed.
