### ISSUE TITLE
key error: 34445555

### ISSUE THREAD

**Issue by yueyilia** [datamllab/rlcard#27]
It seems that '33334444' is legal for four_two_pair type, and '3333444555' is legal for trio_pair_chain_2 type, but '34445555' is illegal for trio_solo_chain_2 type. is it a bug？

**Comment by daochenzha** [comment]
Hi, @yueyilia Thank you for the report. We will double-check this issue soon.

**Comment by CaoYuanpu** [comment]
Hi, @yueyilia  The point of solo cards in this type needs to be different from trio cards. You can see the official rules in the link. http://www.imsa.cn/archives/40177

**Comment by yueyilia** [comment]
![1](https://user-images.githubusercontent.com/39787440/68739989-1723cc00-0625-11ea-814f-09058aa56167.png)
According to the rule, "33334444": [["four_two_pair", 1] and "555666777888": [["trio_solo_chain_3", 3], ["trio_solo_chain_3", 4]] are illegal.

**Comment by daochenzha** [comment]
Hi @yueyilia We confirm that it should be a bug. We will fix it soon. Thank you for letting us know :)

**Comment by daochenzha** [comment]
@yueyilia Bug fixes. Thanks.
