### ISSUE TITLE
Bridge hidden card rep error

### ISSUE THREAD

**Issue by YanSong97** [datamllab/rlcard#276]
Great lib! 

In bridge environment, the hidden card representation seems to have the incorrect `hidden_player_ids` for a four-player game. Correct me if am wrong, I believe line 237 should be something like `hidden_player_ids = [(current_player_id + 1) % 4, (current_player_id + 3) % 4] ` to get the correct hidden player id. Same applies to line 239.

Appreciate it if you can double-check it.

 https://github.com/datamllab/rlcard/blob/517cb08f8b383ad113492425c9377ca4b9680c74/rlcard/envs/bridge.py#L232-L247

**Comment by billh0420** [comment]
Thanks for finding this error. I corrected the two lines and submitted a pull request.

**Comment by daochenzha** [comment]
@billh0420 @YanSong97 Thanks for the fix!
