### ISSUE TITLE
Should PyPi be updating rlcard package?

### ISSUE THREAD

**Issue by billh0420** [datamllab/rlcard#282]
The latest version of richard that PyPi has is dated Jan 13, 2023. Should this be updated?

When I do "pip install rlcard" I don't get the latest version. I assume that pip is trying to pull from PyPi.

**Comment by daochenzha** [comment]
@billh0420 Thank you for the reminder. I will update it once this PR is merged. https://github.com/datamllab/rlcard/pull/280

**Comment by hsywhu** [comment]
New version has been published on pypi
