### ISSUE TITLE
how to use the pretrained model

### ISSUE THREAD

**Issue by sunnyForIOS** [datamllab/rlcard#29]
how to use the pretrained model, such as nfsp agents. i want to play doudizhu with 3 players, all of them load the pretrained model

**Comment by daochenzha** [comment]
@sunnyForIOS I suggest following the example of loading NFSP for Leduc:

https://github.com/datamllab/rlcard/blob/master/rlcard/models/pretrained_models.py

**Comment by sunnyForIOS** [comment]
a nfsp model is trained for 3 players together,or each player train a separate model

**Comment by daochenzha** [comment]
Each player has a separate model. Thus, actually, 3 models are saved, and should be loaded accordingly.

**Comment by sunnyForIOS** [comment]
for i in range(env.player_num):
        agent = NFSPAgent(sess,

saver.save(sess, 'models/doudizhu_nfsp/model')

each player use the same sess which is save by the saver, and how to save 3 models, if i use saver.save ,only one model will be save

**Comment by daochenzha** [comment]
The models have different name scopes. Check the scope argument of NFSP.

**Comment by sunnyForIOS** [comment]
you are right ,scope is different . in save stage,use saver.save, one model saved, right?  in reload stage, saver restore ,agent will load params by their own name scope, right?

**Comment by daochenzha** [comment]
Yes. `saver.restore` will restore the parameters of all the scopes in the entire graph.

**Comment by sunnyForIOS** [comment]
thanks very much
