### ISSUE TITLE
how to train mahjong game?

### ISSUE THREAD

**Issue by jacy** [datamllab/rlcard#298]

**Comment by daochenzha** [comment]
@jacy Just need to change the env to mahjong. Note that the state and action features of Mahjong are not well-engineered. So to achieve a better performance, it is recommended to spend more effort on the feature design.

**Comment by jacy** [comment]
hi @daochenzha, is it just to use the random model to train?

**Comment by daochenzha** [comment]
@jacy Yes, you should be able to see reward improvement with a random model. But it could not be satisfactory because the features are not well-engineered.

**Comment by jacy** [comment]
ahh ok, seems it might still need to take lots of effort to train it reach to  a normal human level

**Comment by jacy** [comment]
have been training mahjong game using DMC, seems the rewards didn't improve even train for several days, anyone can shed some light?
