### ISSUE TITLE
adding-models.md

### ISSUE THREAD

**Issue by sunnyForIOS** [datamllab/rlcard#30]
<Wrap models. You need to inherit the Model class in rlcard/models.model.py. Then put all the models for the players into a list. Rewrite get_agent function and return this list.> can not find the **get_agent** function

<Load the model in environment. To load the model, modify load_pretrained_models in the corresponding game environment in rlcard/envs. Use the resgistered name to load the model.>
can not find **load_pretrained_models** function

**Comment by daochenzha** [comment]
Thank you for pointing out. The documents have been updated. Let me know if you have further questions.
