### ISSUE TITLE
How can i play doudizhu with AI

### ISSUE THREAD

**Issue by loserZhang** [datamllab/rlcard#33]
Doudizhu needs three-person, how can I play with two ai in this game?

**Comment by daochenzha** [comment]
@loserZhang Currently, we do not have human interface for Dou Dizhu. If you would like to play with doudizhu AI, I suggest implementing a simple human interface following the examples of UNO or Leduc. We are developing GUI for the games. Dou Dizhu human interface will be available once finished.

**Comment by loserZhang** [comment]
OK，thank you.
