### ISSUE TITLE
How can i encode my action in doudizhu?

### ISSUE THREAD

**Issue by loserZhang** [datamllab/rlcard#37]
For example, as a human player,  I choose 5553. What is my encoded action in [0, 308]?

**Comment by sunnyForIOS** [comment]
555* ?

**Comment by sunnyForIOS** [comment]
@loserZhang qq276749553, we can learn together

**Comment by daochenzha** [comment]
@loserZhang It is a good question. As a human, we may not need to encode actions. The idea of encoding actions is to reduce the action space to make it feasible for learning-based agents. As humans, we don't need any action abstraction. Thus, we may bypass `Env` and directly pass 5553 to `Game`.

**Comment by loserZhang** [comment]
thank you very much------------------ 原始邮件 ------------------
发件人: "Daochen Zha"<notifications@github.com>
发送时间: 2019年11月23日(星期六) 凌晨0:43
收件人: "datamllab/rlcard"<rlcard@noreply.github.com>;
抄送: "loserZhang"<1303784270@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [datamllab/rlcard] How can i encode my action in doudizhu? (#37)



@loserZhang It is a good question. As a human, we may not need to encode actions. The idea of encoding actions is to reduce the action space to make it feasible for learning-based agents. As humans, we don't need any action abstraction. Thus, we may bypass Env and directly pass 5553 to Game.
 
&mdash;
