### ISSUE TITLE
 rule-based AI for Dou Dizhu can guidance the agent train with astrict actions?

### ISSUE THREAD

**Issue by sunnyForIOS** [datamllab/rlcard#51]
rule-based AI for Dou Dizhu maybe help the agent train with reasonable actions ? improve rate of convergence?

**Comment by daochenzha** [comment]
@sunnyForIOS I think so. One way could be to generate self-play data with rules. We can use supervised learning to train an initial model. Then keep training the model with NFSP or DQN.

We are developing some rules, which should be available around the end of this year.

**Comment by sunnyForIOS** [comment]
so should we change the kicker net such as three with one, because the RHCP AI do not decode the kicker action with the same method which we use now . by the way ,I have a idea, when any player has only two or one card, we can use guess his handcards then use mcst to train replace the previous net,

**Comment by daochenzha** [comment]
@sunnyForIOS I agree that using mcts when any player has only two or one hands would be a good idea. The search space is reasonable for mcts, which may deliver better performance than the neural net.

I kicker net could also be trained based on the rules? But I am not sure whether it is applicable or not.

**Comment by sunnyForIOS** [comment]
[Combinational Q-Learning for Dou Di Zhu](https://paperswithcode.com/paper/combinational-q-learning-for-dou-di-zhu) in this paper the rule-based AI RHCP player is nomel level except no cooperate 
maybe you had read it

**Comment by daochenzha** [comment]
Yeah, I have read this paper. RHCP seems to be a good rule baseline to guide the agent.
