### ISSUE TITLE
torch or pytorch at setup.py

### ISSUE THREAD

**Issue by yptheangel** [datamllab/rlcard#53]
Facing issue when trying to install torch,  my workaround is to uncomment torch at setup.py

I saw this error when running `pip install -e .` 
```
ERROR: Could not find a version that satisfies the requirement torch>=1.3 (from rlcard==0.1.6) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch>=1.3 (from rlcard==0.1.6)
```
blackjack env works fine without torch.

Setup Versions:
conda 4.7.11
Python 3.7.5

**Comment by daochenzha** [comment]
@yptheangel Hello, torch is not a requirement for most of the functionalities. It is only needed if you would like to try PyTorch implementation of DQN and NFSP. Thanks for reporting the issue. We will check it out and fix it in setup.

**Comment by hsywhu** [comment]
Hi @yptheangel , we found the install script does have problem with installing PyTorch on specific systems like Windows. We have set PyTorch as extra requirement in the script. If you want to try out our Pytorch features, you may follow the instruction on PyTorch official website to install it manually. Thanks again for reporting the issue.

**Comment by yptheangel** [comment]
thanks @hsywhu @daochenzha
