### ISSUE TITLE
Normalize the state

### ISSUE THREAD

**Issue by lujiayou123** [datamllab/rlcard#57]
LaoTie,clould you give an example of No-Limit Texas Holdem to help me understand how the "Normalizer" works?

**Comment by daochenzha** [comment]
@lujiayou123 Hi, the normalizer will collect some states with random play, and obtain a mean and a standard error for the collected states.

Then for the upcoming states, we normalize them by (state-mean)/std such that they are in the same scale. It is a trick to make the training more stable.

**Comment by sddi** [comment]
I see the state usually set 0 or 1, 1 means use, 0 means not. So, Is normalization necessary?

**Comment by daochenzha** [comment]
@sddi We didn't try running it without normalization. In this case, it may or may not necessary.
