### ISSUE TITLE
Is there an example about subgame solving

### ISSUE THREAD

**Issue by menglinjian** [datamllab/rlcard#60]

**Comment by daochenzha** [comment]
@menglinjian Hi, we do not have subgame solving in the current version. Currently, we only include several basic algorithms.

**Comment by menglinjian** [comment]
@daochenzha  I have another question about your code in CFR agent. In the original paper of CFR, the writers used the counterfactual utility instead of  expected value in your code.

**Comment by daochenzha** [comment]
@menglinjian The expected value is weighted by counterfactual_prob, thus it is counterfactual utility.
