### ISSUE TITLE
module 'torch.nn' has no attribute 'Flatten'

### ISSUE THREAD

**Issue by OleVoss** [datamllab/rlcard#61]
`agent = dqn_agent_pytorch.DQNAgent("dqn {}".format(i),
                                      action_num=env.action_num,
                                      state_shape=env.state_shape,
                                      mlp_layers=[128,128])`

When trying to initialize some dqn pytorch agents I am getting the above error.
Am I doing sth. wrong here? And how can I solve the issue?

Edit:
In general are there some guides on how to build my own games and how to use pytorch for training?

**Comment by daochenzha** [comment]
@OleVoss Hi there. Thank you for providing feedbacks. To build a new game, you could generally follow this doc https://github.com/datamllab/rlcard/blob/master/docs/adding-new-environments.md Let me know if you have further questions.

For pytorch, one may simply look into examples such as https://github.com/datamllab/rlcard/blob/master/examples/limit_holdem_dqn_pytorch.py 

For the proposed bug, it seems to be a dependency issue. We will check it shortly. Thank you!
