### ISSUE TITLE
PyPI Release?

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#69]
Hey, could you please release this library on PyPI, so people can just do `pip install rlcard` instead of having to clone the repo first? It makes it easier to use your code.

Specifically, I'm going to release an RL library on PyPI soon using various RL environment libraries. I'd like it use rlcard in addition to others, but to depend on rlcard it would have to either be included with my package (which is undesirable) or be installed from pip per a requirements.txt file (and thus hosted on PyPI).

**Comment by hsywhu** [comment]
Hi @justinkterry , thanks for bringing this up. We have uploaded the newest version of RLCard on PyPI just now. You can try to install it with `pip install rlcard==0.1.9`.

**Comment by justinkterry** [comment]
That's awesome, thanks a ton. You'll probably want to change the readme to switch over to the regular PyPI install as well.

**Comment by daochenzha** [comment]
Thank you @justinkterry We will push an update to the library soon (see dev branch). PyPI install is already added to the readme in the dev branch, which will soon be merged to master.
