### ISSUE TITLE
老乡，您好。请问怎么获得斗地主的训练数据？

### ISSUE THREAD

**Issue by liu6023952** [datamllab/rlcard#73]
老乡，您好。请问怎么获得斗地主的训练数据？能否发布一个简单demo，实现斗地主人机对战。非常感谢！

**Comment by daochenzha** [comment]
Hi, @liu6023952 Good questions!

For the training data, you can use `run` function to obtain data. In the example of https://github.com/datamllab/rlcard/blob/master/examples/doudizhu_random.py, the data are obtained by playing with random agents. We can also generate data with other agents. For example, we have recently implemented a rule agent in dev branch. See https://github.com/datamllab/rlcard/blob/dev/rlcard/models/doudizhu_rule_models.py. 

For the demo, we currently support a GUI for replay in another repo https://github.com/datamllab/rlcard-showdown This project is under final testing and will be released soon. But we do not support human-agent GUI for now. We may add this demo to the rlcard-showdown repo in the future.
