### ISSUE TITLE
How to save DQNAgent and NFSPAgent?

### ISSUE THREAD

**Issue by lxxxxfdh** [datamllab/rlcard#75]
Hi, I want to ask how to save and load the DQNAgent and NFSPAgent such that we can reuse it once the training is finished.

Thanks!

**Comment by lxxxxfdh** [comment]
Sorry, I did not found the pretrained_models.py before.
I will close this issue.

**Comment by daochenzha** [comment]
@lxxxxfdh Hi, thank you for the feedback. I have added clearer examples in the dev branch. https://github.com/datamllab/rlcard/blob/dev/examples/leduc_holdem_nfsp_load_model.py
Hopefully, it could help.

**Comment by myluoxz** [comment]
Will keras version be added in the future ?
