### ISSUE TITLE
pip packaging issue

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#79]
Your actual environments only depend on numpy and matplotlib. When you install rlcard via pip, it's because you're using the environments as part of a larger thing (in my case as a dependency of a package I'm going to release), not because you want to reproduce experiments with sample code. 

The specific problem I have is that, as previously mentioned, I'm releasing a large library that depends on rlcard. Having that library in turn depend on tensorflow, tensorflow probability and sonnet is undesirable for me, as it will be for many people who'd like to use rlcard environments (the main use case), especially since you restrict TF to 1.14 or 1.15. 

Can you remove those as requirements of RLCard in the PyPI release? Per the above, I think that removing the demo code from the PyPI release or having people install an additional appropriate version of tensorflow etc would be what you'd normally do in a situation like this.

**Comment by hsywhu** [comment]
Hi @justinkterry , thanks for your suggestion. We just merged our new functionalities to the master branch and uploaded a new version of RLcard to PyPI, within which we have set Tensorflow and related packages as extra requirements. You can try it with `pip install rlcard==0.1.10`.

**Comment by lssr** [comment]
Hi @hsywhu, thanks for the quick response. I installed RLCard as you suggested but I am now getting the following error: `ModuleNotFoundError: No module named 'rlcard.games.gin_rummy.utils'`. It looks like version 0.1.10 is missing a folder named `utils` inside `games/gin_rummy`.

**Comment by hsywhu** [comment]
@lssr , you're right, I have had it fixed. Can you try again with `pip install rlcard==0.1.11`?

**Comment by justinkterry** [comment]
Hey man, somethings wrong. When I do `pip3 install rlcard` Ubuntu and import rlcard (to just use the environments), I get a tremendous number of tensorflow import warning messages. That should not happen.

Additionally, I get this warning about PyTorch not being installed:

`WAINING: PyTorch not installed. Run "pip install rlcard[torch]" to install PyTorch`

1) Getting that warning makes no sense
2) You spelled warning wrong
3) You used a print statement instead of a proper warning, which is not best practices.

**Comment by justinkterry** [comment]
I think the problem occurs when using `pip3 install rlcard` when tensorflow is already installed.

**Comment by hsywhu** [comment]
@justinkterry  The warning message issue is now fixed. Can you try `pip install rlcard==0.1.12`?
