### ISSUE TITLE
When will a stable version of Gin Rummy be released?

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#81]
Title stands: when can I use Gin Rummy? There's crashes and issues with the reward computation in it's current state.

**Comment by daochenzha** [comment]
Thank you for letting us know. This game is just added. Thus, it may have some bugs. We will work on it.

**Comment by justinkterry** [comment]
I get that. My question is, do you know when a fixed version will be available?

**Comment by daochenzha** [comment]
I am not sure. The code of gin rummy is contributed by @billh0420 It would be easier, if he could take a look at the problem. We will also take a look and try to fix it, but not sure how long it takes.

**Comment by billh0420** [comment]
You can override the reward computation as follows:

`
import rlcard
from rlcard.agents.random_agent import RandomAgent

import rlcard.games.gin_rummy.melding as melding
import rlcard.games.gin_rummy.utils as utils
from rlcard.games.gin_rummy.scorers import Scorer


class MyScorer(Scorer):

    def __init__(self):
        super().__init__(name="MyScorer")

    def get_payoffs(self, game):
        payoffs = [0, 0]
        for player_id in range(2):  # update payoffs for both players
            hand = game.round.players[player_id].hand
            best_meld_clusters = melding.get_best_meld_clusters(hand=hand)
            best_meld_cluster = [] if not best_meld_clusters else best_meld_clusters[0]
            deadwood_count = utils.get_deadwood_count(hand, best_meld_cluster)
            payoffs[player_id] = deadwood_count
        return payoffs


def make_gin_rummy_env() -> 'GinRummyEnv':
    gin_rummy_env = rlcard.make('gin-rummy')
    north_agent = RandomAgent(action_num=gin_rummy_env.action_num)
    south_agent = RandomAgent(action_num=gin_rummy_env.action_num)
    gin_rummy_env.set_agents([north_agent, south_agent])
    my_scorer = MyScorer()
    gin_rummy_env.scorer = my_scorer
    return gin_rummy_env


if __name__ == '__main__':
    gin_rummy_env = make_gin_rummy_env()
    _, payoffs = gin_rummy_env.run()
    print(f"payoffs={payoffs}")
    for move in gin_rummy_env.game.round.move_sheet:
        print(f"{move}")

`

**Comment by lssr** [comment]
@billh0420, thanks for the solution. Also, I see that the solution is already implemented in the Gin Rummy code on GitHub. When should I expect the updated version of Gin Rummy to be available via PyPI?

**Comment by hsywhu** [comment]
@lssr  , the latest version is uploaded to PyPI, you can try it with `pip install rlcard==0.1.13`
