### ISSUE TITLE
Uno is not learning anything?

### ISSUE THREAD

**Issue by CesMak** [datamllab/rlcard#82]
Hey there,

I installed rlcard via **pip install rlcard** when trying the example **uno.py** I had to do some modifications as the code installed with pip was not the most recent one. I got the example to run after small modifications (getting most recent code samples).

**Question**
However after training a long training I still have a very very small reward:

  timestep     |  3939973
  reward       |  0.004

  timestep     |  3945224
  reward       |  0.036
----------------------------------------

  timestep     |  3949951
  reward       |  -0.04

What parameters for training do you use?
How long do you train?
What do I miss?
Does anyone here has different results?

I did not change any params:
```


with tf.Session() as sess:

    # Initialize a global step
    global_step = tf.Variable(0, name='global_step', trainable=False)

    # Set up the agents
    agent = DQNAgent(sess,
                     scope='dqn',
                     action_num=env.action_num,
                     replay_memory_size=20000,
                     replay_memory_init_size=memory_init_size,
                     state_shape=env.state_shape,
                     mlp_layers=[512, 512])
    random_agent = RandomAgent(action_num=eval_env.action_num)
    env.set_agents([agent, random_agent, random_agent, random_agent])
    eval_env.set_agents([agent, random_agent, random_agent, random_agent])

```

**Comment by daochenzha** [comment]
@CesMak In a very old version, this example with the same hyperparameters could have near 0.1 maximum reward at 400000 steps, but the performance decreases afterward. The current version of DQN is a little bit different from the old one. Thus, I am not sure what performance it can achieve.

It is very challenging to train agents on UNO. Firstly, the game itself is hard. Secondly, DQN itself may have some problems. In the old version, the performance of DQN decreases after 400000 steps. This is also a common problem for many other environments.

We will do a hyperparameter search for UNP and update the example later.

**Comment by CesMak** [comment]
What does a reward of 0.1 mean? 

How often wins the trained player? 

Great let me know:) 

Well for this reason I would advise to use PPO or Policy Gradient method this should work a lot better.

**Comment by daochenzha** [comment]
Winning a game receives 1 reward. Losing a game -1 reward. 0.1 is the average reward when playing many games. Yes, it would be nice to also have those baselines.

**Comment by CesMak** [comment]
What is the performance of the  uno_nfsp.py also max reward 0.1?

**Comment by daochenzha** [comment]
The performance is slightly worse than DQN. It may be caused by not enough hyperparameter tuning.
