### ISSUE TITLE
There is a typo in docs

### ISSUE THREAD

**Issue by dayekuaipao** [datamllab/rlcard#86]
http://rlcard.org/games.html#mahjong
'It is commonly played but 4 players. ' should be 'It is commonly played by 4 players. '

**Comment by daochenzha** [comment]
Thanks, we will fix it.

**Comment by dayekuaipao** [comment]
And the example in 'http://rlcard.org/index.html' can not run. It seems the RandomAgent needs a parameter.

**Comment by daochenzha** [comment]
Sorry. We have just updated the library. Some documents are old. You may refer to these examples https://github.com/datamllab/rlcard/blob/master/docs/toy-examples.md#playing-with-random-agents

Thank you for posting this out. We will update those docs as soon as we can.

**Comment by dayekuaipao** [comment]
Ok. xinkule. Thanks for your job.
