### ISSUE TITLE
Getting Started issue

### ISSUE THREAD

**Issue by befeltingu** [datamllab/rlcard#95]
Hello,
       I installed RL Card using `pip install rlcard[tensorflow]` and I also tried the following with `pip install rlcard`. I just copy pasted the "Having fun with pretrained Leduc" example and hit run. I got the following error. 
**AttributeError**: 'LeducholdemEnv' object has no attribute 'set_mode'

I tried an earlier version 0.1.08 and the example worked. 

I am running python 3.7.3 on MacOS. Tensorflow==1.15.2

**Comment by hsywhu** [comment]
Hi @befeltingu , thanks for pointing this out. The problem is caused by out-dated docs. We have updated the doc for the pretrained leduc example, you can try it again on the latest version of RLCard.

**Comment by befeltingu** [comment]
@hsywhu Great thanks that works. Looks like docs on your website are out of date as well FYI.
