### ISSUE TITLE
Please add proper documentation for Gin Rummy

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#97]
Please add proper documentation for Gin Rummy, just like all your other environments have.

**Comment by daochenzha** [comment]
Thank you for the suggestion. Could you which parts of the documents are not clear so that we can improve. Let's have a discussion here. @justinkterry  @billh0420 

Link: https://github.com/datamllab/rlcard/blob/master/docs/games.md#gin-rummy

**Comment by justinkterry** [comment]
I see. It isn't here: http://rlcard.org/games.html#

Has it not propagated to your site yet or something?

**Comment by daochenzha** [comment]
@justinkterry Ok got it. The contents on the site will be updated these two days.

**Comment by hsywhu** [comment]
@justinkterry Website updated

**Comment by justinkterry** [comment]
thanks
