### ISSUE TITLE
Gin Rummy Performance

### ISSUE THREAD

**Issue by justinkterry** [datamllab/rlcard#98]
Similar to issue #91 , Gin Rummy is unusually slow- 5381 turns per second. Can that be improved to be 20k like all the others?

@lssr

**Comment by daochenzha** [comment]
We will check the possibility.

**Comment by justinkterry** [comment]
@billh0420 any thoughts here?

**Comment by billh0420** [comment]
@justinkterry asked "any thoughts here?"

I made a different approach but it didn't improve the time by much.

My goal now is to write out all the moves for 100K games. Then feed this back passing the actions without calculating them. This way I can see how much time is used to perform the actions (and how much time is used to calculate the actions). Hopefully, performing the action shouldn't be the bottleneck (but I want to rule that out). Next, I can then try to let just one type of action be calculated and see which one (or ones) is taken an excessive amount of time.

**Comment by billh0420** [comment]
Changes to improve Gin Rummy speed have been moved to Dev branch. It is about twice as fast. On my computer, I went from 6600 steps per second to 14000 steps per second.

**Comment by justinkterry** [comment]
@billh0420 thanks a ton!
@daochenzha Can this be merged and released on PyPI?

**Comment by justinkterry** [comment]
@daochenzha have you been able to merge this change and release it on PyPI?

**Comment by daochenzha** [comment]
@justinkterry We are working on this. It should be available soon.

**Comment by hsywhu** [comment]
@justinkterry The new version 0.1.17 is now released on PyPI
